// generated by src/lib/package.gen.ts

import type {Package_Json} from '@grogarden/gro/package_json.js';

import type {Src_Json} from '@grogarden/gro/src_json.js';

export const package_json = {
	name: '@fuz.dev/fuz_template',
	version: '0.0.1',
	description:
		'a static web app and Node library template with TypeScript, Svelte, SvelteKit, Vite, esbuild, Fuz, and Gro',
	icon: '❄',
	public: true,
	homepage: 'https://template.fuz.dev/',
	repository: 'https://github.com/fuz-dev/fuz_template',
	type: 'module',
	engines: {node: '>=20.7'},
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		test: 'gro test',
		deploy: 'gro deploy',
	},
	files: ['dist'],
	devDependencies: {
		'@feltjs/eslint-config': '^0.4.1',
		'@fuz.dev/fuz': '^0.80.0',
		'@fuz.dev/fuz_contextmenu': '^0.6.0',
		'@fuz.dev/fuz_dialog': '^0.5.0',
		'@fuz.dev/fuz_library': '^0.21.1',
		'@grogarden/gro': '^0.102.0',
		'@grogarden/util': '^0.16.0',
		'@sveltejs/adapter-static': '^2.0.3',
		'@sveltejs/kit': '^1.27.4',
		'@typescript-eslint/eslint-plugin': '^6.10.0',
		'@typescript-eslint/parser': '^6.10.0',
		eslint: '^8.53.0',
		'eslint-plugin-svelte': '^2.35.0',
		prettier: '^3.0.3',
		'prettier-plugin-svelte': '^3.1.0',
		svelte: '^4.2.3',
		'svelte-check': '^3.6.0',
		tslib: '^2.6.2',
		typescript: '^5.2.2',
		uvu: '^0.5.6',
	},
	eslintConfig: {root: true, extends: '@feltjs'},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
} satisfies Package_Json;

export const src_json = {name: '@fuz.dev/fuz_template', version: '0.0.1'} satisfies Src_Json;

// generated by src/lib/package.gen.ts
