// generated by src/routes/package.gen.ts

import type {Package_Json} from '@ryanatkn/gro/package_json.js';
import type {Src_Json} from '@ryanatkn/gro/src_json.js';

export const package_json = {
	name: '@ryanatkn/fuz_template',
	version: '0.0.1',
	description:
		'a static web app and Node library template with TypeScript, Svelte, SvelteKit, Vite, esbuild, Fuz, and Gro',
	glyph: '❄',
	logo: 'logo.svg',
	logo_alt: 'a friendly pixelated spider facing you',
	public: true,
	homepage: 'https://template.fuz.dev/',
	repository: 'https://github.com/ryanatkn/fuz_template',
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		check: 'gro check',
		test: 'gro test',
		preview: 'vite preview',
		deploy: 'gro deploy',
	},
	type: 'module',
	engines: {node: '>=20.12'},
	devDependencies: {
		'@ryanatkn/belt': '^0.24.12',
		'@ryanatkn/eslint-config': '^0.5.1',
		'@ryanatkn/fuz': '^0.120.4',
		'@ryanatkn/gro': '^0.133.7',
		'@ryanatkn/moss': '^0.13.3',
		'@sveltejs/adapter-static': '^3.0.4',
		'@sveltejs/kit': '^2.5.22',
		'@sveltejs/vite-plugin-svelte': '^3.1.1',
		eslint: '^9.9.0',
		'eslint-plugin-svelte': '^2.43.0',
		prettier: '^3.3.3',
		'prettier-plugin-svelte': '^3.2.6',
		svelte: '^5.0.0-next.221',
		'svelte-check': '^3.8.5',
		tslib: '^2.6.3',
		typescript: '^5.5.4',
		'typescript-eslint': '^8.1.0',
		uvu: '^0.5.6',
	},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
	sideEffects: ['**/*.css'],
	files: ['dist'],
} satisfies Package_Json;

export const src_json = {name: '@ryanatkn/fuz_template', version: '0.0.1'} satisfies Src_Json;

// generated by src/routes/package.gen.ts
