// generated by src/routes/package.gen.ts

import type {Package_Json} from '@grogarden/gro/package_json.js';
import type {Src_Json} from '@grogarden/gro/src_json.js';

export const package_json = {
	name: '@fuz.dev/fuz_template',
	version: '0.0.1',
	description:
		'a static web app and Node library template with TypeScript, Svelte, SvelteKit, Vite, esbuild, Fuz, and Gro',
	icon: '❄',
	public: true,
	homepage: 'https://template.fuz.dev/',
	repository: 'https://github.com/fuz-dev/fuz_template',
	type: 'module',
	engines: {node: '>=20.10'},
	scripts: {
		start: 'gro dev',
		dev: 'gro dev',
		build: 'gro build',
		test: 'gro test',
		deploy: 'gro deploy',
	},
	files: ['dist'],
	devDependencies: {
		'@feltjs/eslint-config': '^0.4.1',
		'@fuz.dev/fuz': '^0.81.0',
		'@fuz.dev/fuz_contextmenu': '^0.7.0',
		'@fuz.dev/fuz_dialog': '^0.6.0',
		'@fuz.dev/fuz_library': '^0.23.0',
		'@grogarden/gro': '^0.108.0',
		'@grogarden/util': '^0.18.3',
		'@sveltejs/adapter-static': '^3.0.1',
		'@sveltejs/kit': '^2.0.6',
		'@sveltejs/vite-plugin-svelte': '^3.0.1',
		'@typescript-eslint/eslint-plugin': '^6.16.0',
		'@typescript-eslint/parser': '^6.16.0',
		eslint: '^8.56.0',
		'eslint-plugin-svelte': '^2.35.1',
		prettier: '^3.1.1',
		'prettier-plugin-svelte': '^3.1.2',
		svelte: '^4.2.8',
		'svelte-check': '^3.6.2',
		tslib: '^2.6.2',
		typescript: '^5.3.3',
		uvu: '^0.5.6',
	},
	eslintConfig: {root: true, extends: '@feltjs'},
	prettier: {
		plugins: ['prettier-plugin-svelte'],
		useTabs: true,
		printWidth: 100,
		singleQuote: true,
		bracketSpacing: false,
		overrides: [{files: 'package.json', options: {useTabs: false}}],
	},
} satisfies Package_Json;

export const src_json = {name: '@fuz.dev/fuz_template', version: '0.0.1'} satisfies Src_Json;

// generated by src/routes/package.gen.ts
